version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: x64
clone_folder: c:\projects\zSoT-DLL\
cache: C:\projects\zsot-dll\bin\x64\Release\zSoT-SDK.lib
build:
  project: C:\projects\zSoT-DLL\zSoT-DLL.sln
  parallel: true
  verbosity: normal